server: 
  port: 8082
 
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3308/db_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  dubbo: 
    application: 
      name: order-provider
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol: 
      name: dubbo
      port: 20880
    scan: 
      com.dubbo.service
