server: 
  port: 8081
 
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3308/db_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  dubbo: 
    application: 
      name: account-provider
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol: 
      name: dubbo
      port: 20881
    scan: 
      com.dubbo.service