server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/db_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
dubbo:
  application:
    name: account-provider
  consumer:
    check: false
  protocol:
    name: dubbo
    port: 20901
  provider:
    retries: 0
    timeout: 60000
  reference:
    check: false
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
  scan:
    basePackages: com.dubbo.service